# This file created by conda-build 25.4.2
# ------------------------------------------------

package:
  name: libcxx
  version: 20.1.4
source:
  - patches:
      - patches/0002-disable-_LIBCPP_AVAILABILITY_HAS_INIT_PRIMARY_EXCEPT.patch
      - patches/0003-Work-around-stray-nostdlib-flags-causing-errors-with.patch
      - patches/0004-patch-__libcpp_tzdb_directory-to-allow-use-on-osx.patch
    sha256: 65e3a582c4c684fa707a56ff643427bce3633eceaceae3295d81c0e830f44b89
    url: https://github.com/llvm/llvm-project/archive/refs/tags/llvmorg-20.1.4.tar.gz
build:
  ignore_run_exports_from:
    - clang_bootstrap_osx-arm64 *
  number: 1
  string: ha82da77_1
requirements:
  build:
    - clang_bootstrap_osx-arm64 20.1.4 h36fe7c2_24
    - macosx_deployment_target_osx-arm64 11.0 h6553868_2
  host:
    - __osx >=11.0
  run:
    - __osx >=11.0
test:
  commands:
    - test -f $PREFIX/lib/libc++.dylib
    - test -f $PREFIX/lib/libc++.a
    - test -f $PREFIX/lib/libc++experimental.a
    - test ! -d $PREFIX/include/c++
about:
  dev_url: https://github.com/llvm/llvm-project
  home: http://libcxx.llvm.org/
  license: Apache-2.0 WITH LLVM-exception
  license_family: Apache
  license_file: libcxx/LICENSE.TXT
  summary: LLVM C++ standard library
extra:
  copy_test_source_files: true
  feedstock-name: libcxx
  final: true
  flow_run_id: azure_20250507.7.1
  recipe-maintainers:
    - SylvainCorlay
    - beckermr
    - h-vetinari
    - inducer
    - isuruf
    - jakirkham
    - timsnyder
  remote_url: https://github.com/conda-forge/libcxx-feedstock
  sha: a18ed4dbc45d08403d555fc44bd5fe3c33e6bc4d
