# This file created by conda-build 25.4.2
# ------------------------------------------------

package:
  name: libsolv
  version: 0.7.32
source:
  fn: libsolv-0.7.32.tar.gz
  patches:
    - add-missing-headers.patch
    - conda_variant_priorization.patch
    - no_error_subdir_mismatch.patch
  sha256: 8c5957fb417823768d70e0faefa6f75f497f41289641256e4fdfecd1954fa16c
  url: https://github.com/openSUSE/libsolv/archive/0.7.32.tar.gz
build:
  number: 2
  run_exports:
    - libsolv >=0.7.32,<0.8.0a0
  string: h13dfb9a_2
requirements:
  build:
    - bzip2 1.0.8 hfdf4475_7
    - c-ares 1.34.5 hf13058a_0
    - ca-certificates 2025.1.31 hbd8a1cb_1
    - cctools_osx-64 1010.6 hd19c6af_6
    - cctools_osx-arm64 1010.6 hd9414f1_6
    - clang 18.1.8 default_h576c50e_9
    - clang-18 18.1.8 default_h3571c67_9
    - clang_impl_osx-arm64 18.1.8 hadf8e89_24
    - clang_osx-arm64 18.1.8 h1728699_24
    - clangxx 18.1.8 default_heb2e8d1_9
    - clangxx_impl_osx-arm64 18.1.8 hd2305f4_24
    - clangxx_osx-arm64 18.1.8 h1728699_24
    - cmake 4.0.1 h477996e_0
    - compiler-rt 18.1.8 h1020d70_1
    - compiler-rt_osx-64 18.1.8 hf2b8a54_1
    - icu 75.1 h120a0e1_0
    - krb5 1.21.3 h37d8d59_0
    - ld64_osx-64 951.9 h33512f0_6
    - ld64_osx-arm64 951.9 h0ae773b_6
    - libclang-cpp18.1 18.1.8 default_h3571c67_9
    - libcurl 8.13.0 h5dec5d8_0
    - libcxx 20.1.3 hf95d169_0
    - libcxx-devel 18.1.8 h7c275be_8
    - libedit 3.1.20250104 pl5321ha958ccf_0
    - libev 4.33 h10d778d_2
    - libexpat 2.7.0 h240833e_0
    - libiconv 1.18 h4b5e92a_1
    - libllvm18 18.1.8 default_h3571c67_5
    - liblzma 5.8.1 hd471939_0
    - libnghttp2 1.64.0 hc7306c3_0
    - libssh2 1.11.1 h3dc7d44_0
    - libuv 1.50.0 h4cb831e_0
    - libxml2 2.14.2 h8c082e5_0
    - libzlib 1.3.1 hd23fc13_2
    - llvm-tools 18.1.8 default_h3571c67_5
    - llvm-tools-18 18.1.8 default_h3571c67_5
    - macosx_deployment_target_osx-arm64 11.0 h6553868_2
    - ncurses 6.5 h0622a9a_3
    - ninja 1.12.1 h3c5361c_0
    - openssl 3.5.0 hc426f3f_0
    - rhash 1.4.5 ha44c9a9_0
    - sigtool 0.1.3 h88f4db0_0
    - tapi 1300.6.5 h390ca13_0
    - zstd 1.5.7 h8210216_2
  host:
    - libcxx 20.1.3 ha82da77_0
    - libzlib 1.3.1 h8359307_2
    - zlib 1.3.1 h8359307_2
  run:
    - __osx >=11.0
    - libcxx >=18
    - libzlib >=1.3.1,<2.0a0
test:
  commands:
    - test -f "${PREFIX}/lib/libsolv${SHLIB_EXT}"
    - test -f "${PREFIX}/lib/libsolvext${SHLIB_EXT}"
    - test -f "${PREFIX}/include/solv/repo.h"
    - dumpsolv -h
    - cmake -G Ninja -S test/ -B build/ -D LIB_NAME="libsolv${SHLIB_EXT}" ${CMAKE_ARGS}
    - cmake --build build/
    - cmake --build build --target test
  files:
    - test/*
  requires:
    - clang_osx-arm64 18.*
    - clangxx_osx-arm64 18.*
    - cmake
    - ninja
about:
  description: libsolv, a free package dependency solver using a satisfiability algorithm.
  dev_url: https://github.com/openSUSE/libsolv
  home: https://github.com/openSUSE/libsolv
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.BSD
  summary: Library for solving packages and reading repositories
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: azure_20250424.2.1
  recipe-maintainers:
    - AntoinePrv
    - JohanMabille
    - SylvainCorlay
    - adriendelsalle
    - davidbrochart
    - pavelzw
    - wolfv
  remote_url: https://github.com/conda-forge/libsolv-feedstock
  sha: 8607fa770ef3c704825bc7d17f1af0d0027d8e92
