# This file created by conda-build 25.4.2
# ------------------------------------------------

package:
  name: openssl
  version: 3.5.0
source:
  sha256: 344d0a79f1a9b08029b0744e2cc401a43f9c90acd1044d09a530b4885a8e9fc0
  url: https://github.com/openssl/openssl/releases/download/openssl-3.5.0/openssl-3.5.0.tar.gz
build:
  number: 1
  run_exports:
    - openssl >=3.5.0,<4.0a0
  string: h81ee809_1
requirements:
  build:
    - clang_bootstrap_osx-arm64 18.1.8 hf1725c4_24
    - macosx_deployment_target_osx-arm64 11.0 h6553868_2
    - make 4.4.1 h00291cd_2
    - perl 5.32.1 7_h10d778d_perl5
  host:
    - __osx >=11.0
  run:
    - __osx >=11.0
    - ca-certificates
test:
  commands:
    - touch checksum.txt
    - $PREFIX/bin/openssl sha256 checksum.txt
    - pkg-config --print-errors --exact-version "3.5.0" openssl
    - if [[ "$(pkg-config --variable=prefix openssl)" == "" ]]; then exit 1; fi
  requires:
    - pkg-config
    - ripgrep
about:
  dev_url: https://github.com/openssl/openssl
  doc_url: https://docs.openssl.org/master/
  home: https://www.openssl.org/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE.txt
  summary: OpenSSL is an open-source implementation of the SSL and TLS protocols
extra:
  copy_test_source_files: true
  feedstock-name: openssl
  final: true
  flow_run_id: azure_20250502.3.1
  recipe-maintainers:
    - h-vetinari
    - jakirkham
    - msarahan
    - ocefpaf
    - pelson
  remote_url: https://github.com/conda-forge/openssl-feedstock
  sha: 4abb9420806c3046b3031e62e40cc5da6969ecac
