# This file created by conda-build 25.3.1
# ------------------------------------------------

package:
  name: libexpat
  version: 2.7.0
source:
  sha256: 10f3e94896cd7f44de566cafa2e0e1f35e8df06d119b38d117c0e72d74a4b4b7
  url: https://github.com/libexpat/libexpat/releases/download/R_2_7_0/expat-2.7.0.tar.bz2
build:
  ignore_run_exports_from:
    - clangxx_osx-arm64 18.*
  number: 0
  string: h286801f_0
requirements:
  build:
    - ca-certificates 2025.1.31 h8857fd0_0
    - cctools_osx-64 1010.6 hd19c6af_4
    - cctools_osx-arm64 1010.6 hd9414f1_4
    - clang 18.1.8 default_h576c50e_8
    - clang-18 18.1.8 default_h3571c67_8
    - clang_impl_osx-arm64 18.1.8 hadf8e89_24
    - clang_osx-arm64 18.1.8 h1728699_24
    - clangxx 18.1.8 default_heb2e8d1_8
    - clangxx_impl_osx-arm64 18.1.8 hd2305f4_24
    - clangxx_osx-arm64 18.1.8 h1728699_24
    - compiler-rt 18.1.8 h1020d70_1
    - compiler-rt_osx-64 18.1.8 hf2b8a54_1
    - gnuconfig 2020.11.07 hd8ed1ab_0
    - icu 75.1 h120a0e1_0
    - ld64_osx-64 951.9 h33512f0_4
    - ld64_osx-arm64 951.9 h0ae773b_4
    - libclang-cpp18.1 18.1.8 default_h3571c67_8
    - libcxx 20.1.1 hf95d169_0
    - libcxx-devel 18.1.8 h7c275be_8
    - libiconv 1.18 h4b5e92a_1
    - libllvm18 18.1.8 hc29ff6c_3
    - liblzma 5.6.4 hd471939_0
    - libxml2 2.13.7 hebb159f_0
    - libzlib 1.3.1 hd23fc13_2
    - llvm-tools 18.1.8 hc29ff6c_3
    - llvm-tools-18 18.1.8 hc29ff6c_3
    - macosx_deployment_target_osx-arm64 11.0 h6553868_2
    - make 4.4.1 h00291cd_2
    - ncurses 6.5 h0622a9a_3
    - openssl 3.4.1 hc426f3f_0
    - sigtool 0.1.3 h88f4db0_0
    - tapi 1300.6.5 h390ca13_0
    - zstd 1.5.7 h8210216_2
  host:
    - __osx >=11.0
  run:
    - __osx >=11.0
  run_constrained:
    - expat 2.7.0.*
test: {}
about:
  home: http://expat.sourceforge.net/
  license: MIT
  license_family: MIT
  license_file: COPYING
  summary: Expat XML parser library in C
extra:
  copy_test_source_files: true
  feedstock-name: expat
  final: true
  flow_run_id: azure_20250331.1.1
  recipe-maintainers:
    - isuruf
    - kwilcox
    - mingwandroid
    - msarahan
    - ocefpaf
    - pelson
    - scopatz
  remote_url: https://github.com/conda-forge/expat-feedstock
  sha: 3a75c3cf2ef3f75b9eeee7635c3e7a97e6668db1
