// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://enimqrakokgvsxddnujn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVuaW1xcmFrb2tndnN4ZGRudWpuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg2NDMxMDEsImV4cCI6MjA2NDIxOTEwMX0.PGgwYxQ0ZgrSQa8E9E0VJYmEQHN6AmohgDRTl5zJoWI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);